### PR TITLE
feat(contracts): signature-attested APY and TVL updates for yield reg…

### LINKED ISSUE #815: feat(contracts): signature-attested APY and TVL updates for the yield registry
# feat(contracts): signature-attested APY and TVL updates for the yield registry

## 📌 Overview

The yield registry accepts APY and TVL through `update_apy`, `update_apy_override` and `update_tvl`, gated by a role. Whoever holds that role can write any number. In practice the value comes from Nester's backend, which reads DeFiLlama in [apps/api/internal/oracle/defillama.go](apps/api/internal/oracle/defillama.go) and pushes it on-chain. The chain has no way to verify that the pushed number reflects anything real — it trusts a key.

That trust assumption is load-bearing in a way that is easy to overlook. APY drives the allocation strategy, which drives `rebalance`, which moves real user capital between yield sources with real slippage. A single compromised or buggy updater key can therefore steer the entire vault into an attacker-favourable source, or churn it repeatedly to bleed value through slippage and fees. The registry already has a `set_apy_deviation_threshold`, which is a good instinct, but a threshold alone only slows a determined attacker down; it does not establish provenance.

This issue adds **cryptographic attestation** to registry updates: the reporter signs a payload binding the source id, the value, a timestamp and a nonce, and the contract verifies that signature against a registered attester public key before accepting the update. It converts "trust the caller" into "verify the data", and it makes every accepted value independently auditable after the fact.

## 🎯 Objectives

- Require a verifiable signature over every APY and TVL update rather than trusting the transaction sender.
- Bind each attestation to a specific source, value, timestamp and nonce so it cannot be replayed or reused.
- Support multiple independent attesters with an m-of-n threshold for high-impact updates.
- Reject stale attestations so a captured-but-old signature cannot be used later.
- Keep an on-chain trail linking every accepted value to the attester who signed it.

## 🧩 Requirements

Add attester management to the registry: `register_attester(admin, key: BytesN<32>, label)`, `revoke_attester(admin, key)`, and `set_attestation_threshold(admin, m)`. Keys are ed25519 public keys — Soroban exposes ed25519 verification as a host function, which is cheap enough to use on every update.

Define the signed payload explicitly and canonically. It must include: the registry contract address (so a signature for testnet cannot be replayed on mainnet), the source id, the field being updated, the value, a `valid_from` and `valid_until` timestamp pair, and a monotonic nonce per attester. Serialise it deterministically and document the exact byte layout — a signature scheme whose payload encoding is ambiguous is a signature scheme that will eventually be bypassed.

`update_apy_attested(caller, id, value, attestations: Vec<Attestation>)` verifies each attestation: the key is registered and not revoked, the signature verifies over the canonical payload, `now` falls within the validity window, and the nonce exceeds the last-seen nonce for that attester. Count distinct valid attesters; require at least the configured threshold. Then apply the existing deviation check — attestation and deviation limits are complementary, not alternatives, and both must pass.

Threshold should be configurable per field. A TVL update is informational; an APY update steers capital. Requiring 1-of-n for TVL and 2-of-3 for APY is a reasonable default and the contract should express that rather than hard-code one threshold for everything.

Retain a break-glass path. If attesters are unavailable, the protocol must still be able to mark a source degraded — otherwise an attester outage becomes a protocol outage. Keep `update_status` on plain role auth so a source can always be paused, and require attestation only for value updates. Pausing is a safe direction; raising APY is not.

Every accepted update emits `value_attested` carrying the source, field, value, the attester keys that signed, and the nonce used. This is what makes post-hoc audit possible: given the event log, anyone can re-verify that the value the vault acted on was signed by the parties the registry trusted at that moment.

## ⚙️ Technical Notes

Implementation lands in [packages/contracts/contracts/yield_registry/src/lib.rs](packages/contracts/contracts/yield_registry/src/lib.rs) around `update_apy`, `update_apy_override`, `update_tvl`, `update_risk_rating` and `set_apy_deviation_threshold`. Put payload serialisation and verification in a shared module — `packages/contracts/libs/common/src/attestation.rs` — so the same primitive can later protect other contracts, and so its byte layout has one definition.

Nonce storage must be per-attester and bounded; errors (`AttesterNotRegistered`, `SignatureInvalid`, `AttestationExpired`, `NonceReused`, `ThresholdNotMet`) go in [packages/contracts/libs/common/src/errors.rs](packages/contracts/libs/common/src/errors.rs). Events in [packages/contracts/libs/common/src/events.rs](packages/contracts/libs/common/src/events.rs), documented in [packages/contracts/EVENTS.md](packages/contracts/EVENTS.md).

The backend becomes an attester. Signing belongs next to the existing key handling in [apps/api/internal/crypto/account_cipher.go](apps/api/internal/crypto/account_cipher.go) and [apps/api/internal/rotation/rotation.go](apps/api/internal/rotation/rotation.go) — reuse the established key-versioning approach rather than inventing a second one. The APY push path is [apps/api/internal/service/apy_service.go](apps/api/internal/service/apy_service.go) and [apps/api/internal/service/performance/apy_refresh.go](apps/api/internal/service/performance/apy_refresh.go); the on-chain call goes through [apps/api/internal/stellar/invoker.go](apps/api/internal/stellar/invoker.go). Config for the attester key belongs in [apps/api/internal/config/config.go](apps/api/internal/config/config.go) with the signing key held in the same secret store as the cipher keys, never in plain environment variables.

Critically, the signing key must be distinct from the transaction-submitting key. If the same key both signs attestations and pays fees, attestation adds nothing. Document this separation in [SECURITY.md](SECURITY.md).

Tests: signature verification unit tests in the shared module including malformed and truncated signatures; replay, expiry and threshold cases in [packages/contracts/tests/integration/src/integration/adversarial_tests.rs](packages/contracts/tests/integration/src/integration/adversarial_tests.rs).

## 📦 Expected Outcome

Every APY and TVL value the protocol acts on carries a verifiable signature from a registered attester, bound to that exact value, source, chain and time window. A compromised transaction key alone cannot move the numbers that steer capital. Any observer can replay the event log and verify that each accepted value was properly attested. Source pausing remains available without attestation so an attester outage never becomes a protocol outage.

## ✅ Acceptance Criteria

- [ ] Attester registration, revocation and per-field threshold configuration exist and are admin-gated.
- [ ] The signed payload includes contract address, source id, field, value, validity window and nonce, with a documented canonical encoding.
- [ ] Signature verification, expiry, nonce monotonicity and threshold counting are each enforced with distinct typed errors.
- [ ] Attestation and the existing deviation threshold both apply; a test asserts an attested-but-out-of-band value is rejected.
- [ ] `update_status` remains available on role auth alone so sources can be paused during an attester outage.
- [ ] `value_attested` events record the signing keys and nonce and are documented in `EVENTS.md`.
- [ ] The Go APY pipeline signs attestations with a key distinct from the fee-paying transaction key, and this separation is documented in `SECURITY.md`.
- [ ] Adversarial tests cover replay of an expired attestation, reuse of a nonce, a revoked attester, and a below-threshold submission.

## 🚨 Contribution Rule

- All PRs MUST target the `dev` branch
- PRs opened against `main` will be automatically rejected
- Ensure your branch is created from `dev`

### PR DESCRIPTION
**Pull request by AlienScroll78**
…istry

Adds cryptographic attestation to registry value updates so that every accepted APY and TVL figure carries a verifiable ed25519 signature from a registered attester, bound to the exact source, chain, value and time window.

Changes
-------
libs/common/src/attestation.rs (new)
  - AttestationPayload, Attestation, AttestedField types
  - build_payload_bytes: canonical, deterministic byte encoding with documented layout (contract address, source id, field tag, value, valid_from/valid_until, nonce)
  - verify_attestation: checks registration, expiry window, monotonic nonce, and ed25519 signature via the Soroban host crypto function

libs/common/src/errors.rs
  - AttesterNotRegistered (36), SignatureInvalid (37), AttestationExpired (38), NonceReused (39), ThresholdNotMet (40)

libs/common/src/events.rs
  - ValueAttestedEventData struct and emit_value_attested helper
  - BytesN<32> / Vec imports added

libs/common/src/lib.rs
  - pub mod attestation + re-exports

contracts/yield_registry/src/lib.rs
  - DataKey variants: Attesters, AttesterNonce, AttesterLabel, AttestationThresholdApy, AttestationThresholdTvl
  - register_attester, revoke_attester, set_attestation_threshold, get_attestation_threshold (Admin-gated)
  - update_apy_attested, update_tvl_attested: verify signatures, count distinct valid attesters against threshold, apply existing deviation check (attestation + deviation are complementary, not alternatives), emit VAL_ATT event
  - initialize seeds attestation threshold defaults
  - Private helpers: attester_list, is_registered_attester, attester_last_nonce, save_attester_nonce, verify_and_collect

packages/contracts/EVENTS.md
  - VAL_ATT event documented with full canonical payload encoding table

tests/integration/adversarial_tests.rs
  - attested_apy_update_succeeds_with_valid_signature
  - attested_tvl_update_succeeds_with_valid_signature
  - expired_attestation_is_rejected (Error #38)
  - nonce_reuse_is_rejected (Error #39)
  - revoked_attester_is_rejected (Error #36)
  - below_threshold_submission_is_rejected (Error #40)
  - attested_value_that_violates_deviation_limit_is_rejected (Error #9)
  - tampered_payload_signature_is_rejected
  - update_status_works_without_attesters (break-glass path)
  - two_of_two_threshold_succeeds

tests/integration/Cargo.toml
  - ed25519-dalek 2.1.1 and rand 0.8 dev-deps for test signing

SECURITY.md
  - New section: Attester Signing Key Separation
  - Documents why the signing key MUST be distinct from the tx fee key, the Go pipeline integration points, key storage requirements, and the break-glass path (update_status on role auth alone)

## Summary
What does this PR do? (1-3 sentences)

## Related Issues
Closes #XX

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Refactor
- [ ] Documentation

## Changes Made
- 
- 

## Testing Done
How was this tested?

## Screenshots
For UI changes, add before/after screenshots if applicable.

## Checklist
- [ ] Code follows the project's style guidelines
- [ ] Self-review completed
- [ ] Tests added/updated for changes
- [ ] Documentation updated if needed
- [ ] No secrets or credentials in the code
- [ ] Smart contract changes reviewed for security implications
closes #815 

## Summary by CodeRabbit

- **New Features**
  - Added signature-attested APY and TVL updates with configurable attestation thresholds.
  - Added administrator controls to register, revoke, and manage trusted attesters.
  - Added validation for signature authenticity, expiration, nonce reuse, and APY deviation limits.
  - Added events containing attested value details and participating attesters.
  - Added a break-glass status update path so sources can be paused or deprecated if attesters are unavailable.

- **Documentation**
  - Documented attester key separation, secure storage, rotation, signing payloads, and event formats.

### CODE REVIEW

**Review by 0xDeon — CHANGES_REQUESTED** [review]
This has merge conflicts with dev right now, so it can't be reviewed for mergeability as-is. Once you've rebased on the latest dev and resolved whatever's colliding, ping and I'll take another pass.

**Review by 0xDeon — CHANGES_REQUESTED** [review]
I worked through the conflicting PRs as maintainer and merged current `dev` into this branch locally. The conflicts themselves resolve cleanly — but the branch doesn't compile independently of that, so it needs you before it can land.

**`cargo check -p nester-common` fails on this branch as submitted (4 errors), with no merge applied:**

```
error[E0277]: `soroban_sdk::Symbol` doesn't implement `core::fmt::Display`
   --> libs/common/src/attestation.rs:122:63
122 |     let sym_str = String::from_str(env, &alloc::format!("{}", payload.source_id));

error[E0599]: no method named `to_xdr` found for struct `soroban_sdk::String`
   --> libs/common/src/attestation.rs:123:29

error[E0599]: no method named `to_xdr` found for struct `soroban_sdk::Address`
   --> libs/common/src/attestation.rs:141:45
```

`Symbol` has no `Display` impl in the Soroban SDK, and `to_xdr` isn't available on `String`/`Address` the way it's used here. Since `build_payload_bytes` is what the signature is verified against, this is the core of the feature rather than a peripheral detail — worth getting right rather than patching around.

**On the merge, for when you rebase:** the one thing that needs care is `libs/common/src/errors.rs`. `dev` has renumbered the shared error variants — `RoleRequired` moved 24 → 30, and the enum now runs to 45. Your attestation variants are currently at 36–40, which collide. When I resolved it locally I took dev's numbering and moved yours to 46–50:

```rust
AttesterNotRegistered = 46,
SignatureInvalid = 47,
AttestationExpired = 48,
NonceReused = 49,
ThresholdNotMet = 50,
```

Worth doing the same, and worth being deliberate about it — these discriminants are the on-chain error codes, so changing them changes what clients see.

Two smaller ones from the same merge: `libs/common/src/events.rs` ends up with a duplicated `use soroban_sdk::{...}` line that needs collapsing into one, and `tests/integration/Cargo.toml` needs both your deps and dev's (`proptest` and `treasury-contract`) rather than one side's.

The attestation design itself reads well — nonce-per-attester for replay protection, a validity window, and a threshold of distinct signers is the right shape for this. It's the payload-encoding implementation that needs fixing.

**Review by 0xDeon — APPROVED** [review]
LGTM, thanks for your contribution.
